<?php

define('CONSUMER_KEY', 'YOUR CONSUMER_KEY'); 
define('CONSUMER_SECRET', 'YOUR CONSUMER_SECRET');
define('ACCESS_TOKEN', 'YOUR ACCESS_TOKEN');
define('ACCESS_SECRET', 'YOUR ACCESS_SECRET');
define('OAUTH_CALLBACK', 'YOUR Callback url');
